FROM ghcr.io/logicethos/duo-sdk-docker:latest

# Build OpenSSL
RUN wget https://www.openssl.org/source/openssl-1.1.1l.tar.gz \
    && tar -xzf openssl-1.1.1l.tar.gz \
    && cd openssl-1.1.1l \
    && ./Configure linux64-riscv64 shared no-asm --prefix=$BUILD_OUTPUT \
    && make && make install

# Build libyaml
WORKDIR /
RUN git clone https://github.com/yaml/libyaml
WORKDIR /libyaml
RUN ./bootstrap
RUN ./configure --host=riscv64-linux-gnu --prefix=$BUILD_OUTPUT \
    && make && make install

# Build gensio
WORKDIR /
RUN git clone https://github.com/cminyard/gensio.git
WORKDIR /gensio
RUN sh reconf
RUN ./configure --host=riscv64-linux-gnu --prefix=$BUILD_OUTPUT \
    && make && make install

## Build ser2net
WORKDIR /
RUN git clone https://github.com/cminyard/ser2net.git
WORKDIR /ser2net
RUN sh reconf
RUN ./configure --host=riscv64-linux-gnu --prefix=$BUILD_OUTPUT \
    && make && make install

WORKDIR $BUILD_OUTPUT

CMD bash