FROM ghcr.io/logicethos/duo-sdk-docker:latest

RUN git clone https://github.com/3cky/mbusd.git
WORKDIR /mbusd
RUN mkdir -p build
WORKDIR /mbusd/build
RUN cmake -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE -DCMAKE_INSTALL_PREFIX=$BUILD_OUT ..
RUN make && make install
RUN cp mbusd $BUILD_OUT/bin/.

WORKDIR $BUILD_OUT
